---
# https://i3wm.org/docs/repositories.html
- name: "Install the needed sur5r-keyring package"
  become: true
  apt:
    deb: "https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2025.03.09_all.deb"
  notify: "linux_apt-get-update"

- meta: flush_handlers

- name: 'Add the i3wm ubuntu repo'
  become: true
  copy:
    dest: '/etc/apt/sources.list.d/i3wm.list'
    content: |
      deb [arch=amd64] http://debian.sur5r.net/i3/ {{ ansible_distribution_release }} universe

    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'linux_apt-get-update'

- name: "Use the i3wm repo only for i3 packages"
  become: true
  copy:
    content: |
      Package: *
      Pin: origin debian.sur5r.net
      Pin-Priority: 100

      Package: i3*
      Pin: origin debian.sur5r.net
      Pin-Priority: 1000
    dest: "/etc/apt/preferences.d/i3wm"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: 'linux_apt-get-update'

- meta: flush_handlers

- name: 'Install i3wm + friends'
  become: true
  apt:
    name:
      - 'i3'
      - 'i3lock'
      - 'i3status'
      - 'hsetroot'
    state: 'present'
