#!/usr/bin/with-contenv bash

# poll every 5 seconds, give up after 12 failures
exec \
    s6-notifyoncheck -d -n 12 -w 5000 -c 'nc -z localhost 8888' \
        /usr/local/bin/sslocal -c /etc/sslocal-config.json

# vi: set ft=bash:
