#!/usr/bin/with-contenv bash

# poll every 5 seconds, give up after 12 failures
exec \
    s6-notifyoncheck -d -n 12 -w 5000 -c 'nc -z 127.0.0.1 8888' \
        /usr/local/bin/sslocal -c /etc/shadowsocks-config.json

# vi: set ft=bash:
