#!/usr/bin/with-contenv bash

echo "[vpn-config] Initializing vpn configuration.."

function set_default() {
  var_name=$1
  var_value=$2

  if [[ -z "${!var_name}" ]]; then
    printf '%s' "${var_value}" > /run/s6/container_environment/${var_name}
  fi
}

##################################
# gluetun defaults:
# - https://github.com/qdm12/gluetun/blob/v3.41.0/Dockerfile
##################################
set_default VPN_SERVICE_PROVIDER "pia"
set_default VPN_TYPE "openvpn"

# Common VPN options
set_default VPN_INTERFACE "tun0"

# OpenVPN
set_default OPENVPN_ENDPOINT_IP ""
set_default OPENVPN_ENDPOINT_PORT ""
set_default OPENVPN_PROTOCOL "udp"
set_default OPENVPN_USER ""
set_default OPENVPN_PASSWORD ""
set_default OPENVPN_USER_SECRETFILE "/run/secrets/openvpn_user"
set_default OPENVPN_PASSWORD_SECRETFILE "/run/secrets/openvpn_password"
set_default OPENVPN_VERSION "2.6"
set_default OPENVPN_VERBOSITY "1"
set_default OPENVPN_FLAGS ""
set_default OPENVPN_CIPHERS ""
set_default OPENVPN_AUTH ""
set_default OPENVPN_PROCESS_USER "root"
set_default OPENVPN_MSSFIX ""
set_default OPENVPN_CUSTOM_CONFIG ""

# Wireguard
set_default WIREGUARD_ENDPOINT_IP ""
set_default WIREGUARD_ENDPOINT_PORT ""
set_default WIREGUARD_CONF_SECRETFILE "/run/secrets/wg0.conf"
set_default WIREGUARD_PRIVATE_KEY ""
set_default WIREGUARD_PRIVATE_KEY_SECRETFILE "/run/secrets/wireguard_private_key"
set_default WIREGUARD_PRESHARED_KEY ""
set_default WIREGUARD_PRESHARED_KEY_SECRETFILE "/run/secrets/wireguard_preshared_key"
set_default WIREGUARD_PUBLIC_KEY ""
set_default WIREGUARD_ALLOWED_IPS ""
set_default WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL "0"
set_default WIREGUARD_ADDRESSES ""
set_default WIREGUARD_ADDRESSES_SECRETFILE "/run/secrets/wireguard_addresses"
set_default WIREGUARD_MTU "1320"
set_default WIREGUARD_IMPLEMENTATION "auto"

# VPN server filtering
set_default SERVER_REGIONS ""
set_default SERVER_COUNTRIES ""
set_default SERVER_CITIES ""
set_default SERVER_HOSTNAMES ""
set_default SERVER_CATEGORIES ""

# Mullvad only:
set_default ISP ""
set_default OWNED_ONLY "no"

# Private Internet Access only:
set_default PRIVATE_INTERNET_ACCESS_OPENVPN_ENCRYPTION_PRESET ""
set_default VPN_PORT_FORWARDING "off"
set_default VPN_PORT_FORWARDING_LISTENING_PORT "0"
set_default VPN_PORT_FORWARDING_PROVIDER ""
set_default VPN_PORT_FORWARDING_STATUS_FILE "/tmp/gluetun/forwarded_port"
set_default VPN_PORT_FORWARDING_USERNAME ""
set_default VPN_PORT_FORWARDING_PASSWORD ""
set_default VPN_PORT_FORWARDING_UP_COMMAND ""
set_default VPN_PORT_FORWARDING_DOWN_COMMAND ""

# Cyberghost only:
set_default OPENVPN_CERT ""
set_default OPENVPN_KEY ""
set_default OPENVPN_CLIENTCRT_SECRETFILE "/run/secrets/openvpn_clientcrt"
set_default OPENVPN_CLIENTKEY_SECRETFILE "/run/secrets/openvpn_clientkey"

# VPNSecure only:
set_default OPENVPN_ENCRYPTED_KEY ""
set_default OPENVPN_ENCRYPTED_KEY_SECRETFILE "/run/secrets/openvpn_encrypted_key"
set_default OPENVPN_KEY_PASSPHRASE ""
set_default OPENVPN_KEY_PASSPHRASE_SECRETFILE "/run/secrets/openvpn_key_passphrase"

# Nordvpn only:
set_default SERVER_NUMBER ""

# PIA only:
set_default SERVER_NAMES ""

# VPNUnlimited and ProtonVPN only:
set_default STREAM_ONLY ""
set_default FREE_ONLY ""

# ProtonVPN only:
set_default SECURE_CORE_ONLY ""
set_default TOR_ONLY ""

# Surfshark only:
set_default MULTIHOP_ONLY ""

# VPN Secure only:
set_default PREMIUM_ONLY ""

# PIA and ProtonVPN only:
set_default PORT_FORWARD_ONLY ""

# Firewall
set_default FIREWALL_ENABLED_DISABLING_IT_SHOOTS_YOU_IN_YOUR_FOOT "on"
set_default FIREWALL_VPN_INPUT_PORTS ""
set_default FIREWALL_INPUT_PORTS ""
set_default FIREWALL_OUTBOUND_SUBNETS ""
set_default FIREWALL_DEBUG "off"

# Logging
set_default LOG_LEVEL "info"

# Health
set_default HEALTH_SERVER_ADDRESS "127.0.0.1:9999"
set_default HEALTH_TARGET_ADDRESSES "cloudflare.com:443,github.com:443"
set_default HEALTH_ICMP_TARGET_IPS "1.1.1.1,8.8.8.8"
set_default HEALTH_SMALL_CHECK_TYPE "icmp"
set_default HEALTH_RESTART_VPN "on"

# DNS
set_default DNS_SERVER "on"
set_default DNS_UPSTREAM_RESOLVER_TYPE "DoT"
set_default DNS_UPSTREAM_RESOLVERS "cloudflare"
set_default DNS_BLOCK_IPS ""
set_default DNS_BLOCK_IP_PREFIXES ""
set_default DNS_CACHING "on"
set_default DNS_UPSTREAM_IPV6 "off"
set_default BLOCK_MALICIOUS "on"
set_default BLOCK_SURVEILLANCE "off"
set_default BLOCK_ADS "off"
set_default DNS_UNBLOCK_HOSTNAMES ""
set_default DNS_REBINDING_PROTECTION_EXEMPT_HOSTNAMES ""
set_default DNS_UPDATE_PERIOD "24h"
set_default DNS_ADDRESS "127.0.0.1"
set_default DNS_KEEP_NAMESERVER "off"

# HTTP proxy
set_default HTTPPROXY ""
set_default HTTPPROXY_LOG "off"
set_default HTTPPROXY_LISTENING_ADDRESS ":8888"
set_default HTTPPROXY_STEALTH "off"
set_default HTTPPROXY_USER ""
set_default HTTPPROXY_PASSWORD ""
set_default HTTPPROXY_USER_SECRETFILE "/run/secrets/httpproxy_user"
set_default HTTPPROXY_PASSWORD_SECRETFILE "/run/secrets/httpproxy_password"

# Shadowsocks
set_default SHADOWSOCKS "off"
set_default SHADOWSOCKS_LOG "off"
set_default SHADOWSOCKS_LISTENING_ADDRESS ":8388"
set_default SHADOWSOCKS_PASSWORD ""
set_default SHADOWSOCKS_PASSWORD_SECRETFILE "/run/secrets/shadowsocks_password"
set_default SHADOWSOCKS_CIPHER "chacha20-ietf-poly1305"

# Control server
set_default HTTP_CONTROL_SERVER_LOG "on"
set_default HTTP_CONTROL_SERVER_ADDRESS ":8000"
set_default HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH "/gluetun/auth/config.toml"
set_default HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE "{}"

# Server data updater
set_default UPDATER_PERIOD "0"
set_default UPDATER_MIN_RATIO "0.8"
set_default UPDATER_VPN_SERVICE_PROVIDERS ""
set_default UPDATER_PROTONVPN_EMAIL ""
set_default UPDATER_PROTONVPN_PASSWORD ""

# Public IP
set_default PUBLICIP_FILE "/tmp/gluetun/ip"
set_default PUBLICIP_ENABLED "on"
set_default PUBLICIP_API "ipinfo,ifconfigco,ip2location,cloudflare"
set_default PUBLICIP_API_TOKEN ""

# Storage
set_default STORAGE_FILEPATH "/gluetun/servers.json"

# Pprof
set_default PPROF_ENABLED "no"
set_default PPROF_BLOCK_PROFILE_RATE "0"
set_default PPROF_MUTEX_PROFILE_RATE "0"
set_default PPROF_HTTP_SERVER_ADDRESS ":6060"

# Extras
set_default VERSION_INFORMATION "on"
set_default TZ ""
set_default PUID "1000"
set_default PGID "1000"

# Configure gluetun & the shadowsocks server
set_default SHADOWSOCKS "on"
set_default SHADOWSOCKS_LOG "off"
set_default SHADOWSOCKS_LISTENING_ADDRESS "0.0.0.0:8388"
ss_cipher="${SHADOWSOCKS_CIPHER:-aes-256-gcm}"
set_default SHADOWSOCKS_CIPHER "${ss_cipher}"
random_shadowsocks_pwd=$(openssl rand -hex 20)
ss_pwd="${SHADOWSOCKS_PASSWORD:-$random_shadowsocks_pwd}"
set_default SHADOWSOCKS_PASSWORD "${ss_pwd}"

# shadowsocks local (client) config
cat << EOF > /etc/sslocal-config.json
{
  "server": "127.0.0.1",
  "server_port": 8388,
  "local_address": "0.0.0.0",
  "local_port": 8888,
  "mode": "tcp_and_udp",
  "method": "${ss_cipher}",
  "password": "${ss_pwd}"
}
EOF

echo "[vpn-config] Waiting until an internet connection is established.."
# Loop until an active internet connection is established
until $(curl --max-time 60 -s -o /dev/null https://cloudflare.com/); do
  # Sleep to allow cooldown
  sleep 10
done

echo "[vpn-config] Updating gluetun VPN server list.."
/usr/local/bin/gluetun update -enduser -providers protonvpn
/usr/local/bin/gluetun update -enduser -providers windscribe

echo "[vpn-config] Installing dnsbl-checker.py.."
cp /etc/dnsbl-checker.py /usr/local/bin/dnsbl-checker
chmod 0755 /usr/local/bin/dnsbl-checker
apk add --update --no-cache python3 py3-pip
ln -sf python3 /usr/bin/python
pip install --break-system-packages --root-user-action=ignore requests dnspython

# gluetun api auth config
mkdir -p /gluetun/auth
cat << EOF > /gluetun/auth/config.toml
[[roles]]
name = "control-server"
# Define a list of routes with the syntax "Http-Method /path"
routes = ["GET /v1/publicip/ip", "GET /v1/portforward"]
auth = "none"
EOF

echo "[vpn-config] VPN configuration complete"

# vi: set ft=bash:
