#!/usr/bin/env bash

filename=$1

# Use the ansible vault password file if it exists
if [[ -e "$ANSIBLE_VAULT_PASSWORD_FILE" ]]; then
  ansible-vault decrypt --output - "$filename" 2>/dev/null || cat "$filename"
else
  cat "$filename"
fi
