---
name: "Latest DNS Proxy Release"

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "*"

  schedule:
    # run this job at 08:00hrs every day
    - cron:  "0 8 * * *"

permissions:
  contents: "read"
  packages: "write"

jobs:
  gh_latest:
    runs-on: "ubuntu-latest"
    env:
      UBUNTU_LTS_VERSION: "20.04"
    steps:
      - name: "Free disk space"
        uses: "jlumbroso/free-disk-space@v1.3.1"
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - uses: "actions/checkout@v4.1.5"
        with:
          lfs: true
          fetch-depth: 0

      - name: "Retrieve the short SHA"
        id: "sha"
        run: echo "value=$(echo ${GITHUB_SHA::8})" >> "$GITHUB_OUTPUT"

      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v3"

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v3"

      - name: "Login to GitHub Container Registry"
        uses: "docker/login-action@v3.1.0"
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Publish to GitHub Packages"
        uses: "docker/build-push-action@v5"
        with:
          context: "./dnsproxy-container"
          file: "./dnsproxy-container/Dockerfile"
          platforms: "linux/amd64"
          push: true
          tags: |
            ghcr.io/marvinpinto/dnsproxy:latest
