---
name: "Tests"

on:
  push:
    branches-ignore:
      - "main"

jobs:
  gh_tests:
    runs-on: "ubuntu-latest"
    env:
      UBUNTU_LTS_VERSION: "20.04"
    steps:
      - name: "Free disk space"
        uses: "jlumbroso/free-disk-space@v1.3.1"
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - uses: "actions/checkout@v4.2.2"
        with:
          lfs: true
          fetch-depth: 0

      - name: "Retrieve the short SHA"
        id: "sha"
        run: echo "value=$(echo ${GITHUB_SHA::8})" >> "$GITHUB_OUTPUT"

      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v3"

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v3"

      - name: "Build the kitchensink container"
        uses: "docker/build-push-action@v6"
        with:
          context: "."
          file: "./Dockerfile"
          build-args: |
            UBUNTU_VERSION=${{ env.UBUNTU_LTS_VERSION }}
          platforms: "linux/amd64"
          load: true
          tags: |
            ghcr.io/marvinpinto/kitchensink:${{ env.UBUNTU_LTS_VERSION }}-latest
            ghcr.io/marvinpinto/kitchensink:${{ env.UBUNTU_LTS_VERSION }}-${{ steps.sha.outputs.value }}

      - name: "Build the vpn container"
        uses: "docker/build-push-action@v6"
        with:
          context: "./vpn-container"
          file: "./vpn-container/Dockerfile"
          platforms: "linux/amd64"
          load: true
          tags: |
            ghcr.io/marvinpinto/vpn:latest

      - name: "Build the dnsproxy container"
        uses: "docker/build-push-action@v6"
        with:
          context: "./dnsproxy-container"
          file: "./dnsproxy-container/Dockerfile"
          platforms: "linux/amd64"
          load: true
          tags: |
            ghcr.io/marvinpinto/dnsproxy:latest
